const qs=[
["Что ребёнок чаще выбирает сам, когда есть свободное время?",["Разбираться, как устроены игры, сайты или техника","Рисовать, монтировать, придумывать визуалы","Собирать, конструировать, чинить","Общаться, выступать, учить языки"]],
["Какая задача его скорее увлечёт?",["Написать программу, которая что-то делает","Придумать интерфейс нового приложения","Собрать устройство с датчиками","Подготовить презентацию для международной аудитории"]],
["Как он относится к новым AI-инструментам?",["Хочет понять, как они работают и автоматизировать задачи","Использует для картинок, идей и творчества","Интересно соединить AI с устройством или роботом","Интересно применять для учёбы и языков"]],
["Что приносит больше удовлетворения?",["Найти ошибку и заставить систему работать","Сделать красиво и удобно","Увидеть, как физический механизм ожил","Убедительно объяснить идею другим"]],
["Если предложить создать игру, что заинтересует сильнее?",["Код и игровая логика","Персонажи, мир и визуальный стиль","Контроллер или физическое устройство для игры","Сюжет, диалоги и презентация"]],
["Как ребёнок обычно решает сложную задачу?",["Разбивает её на шаги и ищет закономерность","Пробует нестандартные идеи и варианты","Экспериментирует руками и проверяет","Обсуждает, ищет информацию и задаёт вопросы"]],
["Что ему ближе на школьном проекте?",["Таблицы, логика, вычисления","Оформление и креативная концепция","Макет, модель, эксперимент","Защита проекта и работа с командой"]],
["Какой кружок он бы выбрал скорее?",["Python / разработка","Дизайн / видео / 3D","Робототехника / электроника","Английский / дебаты / международный клуб"]],
["Что ребёнок любит улучшать?",["Скорость и функциональность","Внешний вид и пользовательский опыт","Конструкцию и механизм","Текст, аргументы и коммуникацию"]],
["Какой результат проекта радует больше?",["Работающее приложение","Красивый цифровой продукт","Работающий робот или устройство","Успешное выступление или командный результат"]],
["Что он смотрит с большим интересом?",["Разборы технологий и программирования","Дизайн, анимацию, digital-креатив","Научные эксперименты и инженерные видео","Истории людей, стран, языков и профессий"]],
["Какая роль в команде кажется естественнее?",["Разработчик / аналитик","Дизайнер / креатор","Инженер / прототипировщик","Организатор / коммуникатор"]],
["Если что-то не работает, первая реакция?",["Искать ошибку в логике","Попробовать другой способ или концепцию","Разобрать и проверить детали","Спросить, исследовать и собрать мнения"]],
["Какой навык хотелось бы усилить в ближайший год?",["Кодинг и AI","Дизайн и создание контента","Инженерное мышление","Английский и уверенную коммуникацию"]],
["Какой проект ребёнок с большей вероятностью покажет друзьям?",["Своё приложение или AI-бота","Свой дизайн, ролик или 3D-проект","Своего робота или умное устройство","Проект на английском или командную инициативу"]]
];
const cats=["tech","creative","engineering","global"], names={tech:"Технологический исследователь",creative:"Digital-креатор",engineering:"Инженер-практик",global:"Глобальный коммуникатор"};
const desc={tech:"Ребёнка привлекают логика, цифровые системы, код и поиск работающих решений.",creative:"Сильный интерес к идеям, визуальному мышлению и созданию цифровых продуктов.",engineering:"Выражен интерес к тому, как устроены реальные вещи: сборке, механизмам и экспериментам.",global:"Ребёнка заряжают коммуникация, языки, командная работа и широкий международный контекст."};
const rec={tech:["Programming","Artificial Intelligence","Game Development"],creative:["Design & Digital","Game Development","AI Creator"],engineering:["Robotics","Programming","AI + Robotics"],global:["English & Global","Design & Digital","Project Leadership"]};
let idx=0,scores={tech:0,creative:0,engineering:0,global:0},history=[];
function render(){document.getElementById("progress").textContent=`Вопрос ${idx+1} из ${qs.length}`;document.getElementById("bar").style.width=`${idx/qs.length*100}%`;document.getElementById("qtext").textContent=qs[idx][0];document.getElementById("answers").innerHTML=qs[idx][1].map((a,i)=>`<button class="answer" onclick="pick(${i})">${a}</button>`).join("");document.getElementById("back").style.visibility=idx?"visible":"hidden"}
function pick(i){scores[cats[i]]++;history.push(i);idx++;if(idx>=qs.length)showResult();else render()}
function back(){if(!idx)return;idx--;let i=history.pop();scores[cats[i]]--;render()}
function showResult(){document.getElementById("quiz").classList.add("hidden");let r=document.getElementById("result");r.classList.remove("hidden");let sorted=Object.entries(scores).sort((a,b)=>b[1]-a[1]),top=sorted[0][0];document.getElementById("resultTitle").textContent=names[top];document.getElementById("resultText").textContent=desc[top]+" Это ориентир по ответам родителя, а не окончательный вывод: лучший следующий шаг — дать ребёнку попробовать 2–3 направления на практике.";document.getElementById("scores").innerHTML=sorted.map(([k,v])=>`<div class="score"><label><span>${names[k]}</span><b>${v}/${qs.length}</b></label><div class="scorebar"><i style="width:${v/Math.max(...Object.values(scores))*100}%"></i></div></div>`).join("");document.getElementById("recommend").innerHTML=rec[top].map(x=>`<span class="rec">${x}</span>`).join("");let msg=encodeURIComponent(`Здравствуйте! Мы прошли мини-тест D.Academy@tr. Результат: ${names[top]}. Хотим обсудить направления: ${rec[top].join(", ")}.`);document.getElementById("resultWa").href=`https://wa.me/77759857269?text=${msg}`}
function restart(){idx=0;scores={tech:0,creative:0,engineering:0,global:0};history=[];document.getElementById("result").classList.add("hidden");document.getElementById("quiz").classList.remove("hidden");render();document.getElementById("test").scrollIntoView()}
render();